/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kasir;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Random;
import java.time.format.DateTimeFormatter;
import java.time.LocalDateTime;
import javax.swing.JOptionPane;

/**
 *
 * @author HamFin18
 */
public class Bayar extends javax.swing.JFrame {

    /**
     * Creates new form Bayar
     */
    public Bayar() {
        initComponents();
    }
    
    public Bayar(int a, String [][] barang, String user) {
        initComponents();
        
        jumlah_barang = a;
        keranjang = barang;
        pegawai = user;

        double total = 0;  
        for (int i = 0; i<jumlah_barang; i++)
        {
            total +=Double.valueOf(keranjang[i][4]);           
        }
        pembayaran.setText(String.valueOf(total));
    }
    
    int jumlah_transaksi;
    private String [][] keranjang;
    private int jumlah_barang;
    private String pegawai;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        pembayaran = new javax.swing.JTextField();
        uangBayar = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Kembalian = new javax.swing.JTextField();
        bayarButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Kasir IndoMabar");

        jLabel1.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        jLabel1.setText("Pembayaran");

        jLabel2.setText("Total Pembayaran");

        jLabel3.setText("Uang Bayar");

        uangBayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uangBayarActionPerformed(evt);
            }
        });

        jLabel4.setText("Kembalian");

        bayarButton.setText("Bayar");
        bayarButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bayarButtonMouseClicked(evt);
            }
        });

        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(uangBayar, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                        .addComponent(pembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bayarButton)
                            .addComponent(Kembalian, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(backButton))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(pembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(uangBayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bayarButton)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(Kembalian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(backButton))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void uangBayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uangBayarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_uangBayarActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        //dispose();
        setVisible(false);
    }//GEN-LAST:event_backButtonActionPerformed
 
    private void bayarButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bayarButtonMouseClicked

        Random x = new Random();
        Kontrol.kontrol_detail_transaksi inputDetail = new Kontrol.kontrol_detail_transaksi();
        Tabel.transaksi transaksi = new Tabel.transaksi();
        
        Kontrol.kontrol_transaksi inputTransaksi = new Kontrol.kontrol_transaksi();
        Tabel.detail_transaksi detail = new Tabel.detail_transaksi();
        
        Double total ,bayar;
        String id_transaksi = "TR"+x.nextInt(99999999);
        
        DateTimeFormatter waktu = DateTimeFormatter.ofPattern("yyyy/MM/dd HH:mm:ss");
        LocalDateTime sekarang = LocalDateTime.now();
        
        String query = "select id from login_pegawai where username='"+pegawai+"'";
        String penjaga = null;
        try
        {
         ResultSet rs = inputTransaksi.execQuery(query);
         rs.first();
         penjaga = rs.getString("id");
        }
        catch(SQLException ex)
        {
            System.out.println("Error : "+ex);
        }
        
        total = Double.parseDouble(pembayaran.getText());
        bayar = Double.parseDouble(uangBayar.getText());
        transaksi.set_total_transaksi_transaksi(total);
        transaksi.set_pegawai_transaksi(penjaga);
        transaksi.set_total_bayar_transaksi(bayar);
        transaksi.set_tanggal_transaksi(waktu.format(sekarang));
        transaksi.set_id_transaksi(id_transaksi);
        
        if(bayar>=total)
        {
            inputTransaksi.add_transaksi(transaksi);
            detail.set_id_detail_transaksi(id_transaksi);
            for(int i=0; i<jumlah_barang; i++)
            {
                detail.set_barang_detail_transaksi(keranjang[i][0]);
                detail.set_total_barang_detail_transaksi(Integer.valueOf(keranjang[i][3]));
                detail.set_total_harga_detail_transaksi(Double.valueOf(keranjang[i][4]));
                inputDetail.add_detail_transaksi(detail);
                
                Kembalian.setText(String.valueOf(bayar - total));
                JOptionPane.showMessageDialog(this,"Terimakasih Telah berbelanja di IndoMabar! >.<");
            }
        }
        else
        {
            JOptionPane.showMessageDialog(this,"Uang yang dibayarkan tidak cukup!");
        }
    }//GEN-LAST:event_bayarButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bayar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bayar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bayar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bayar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bayar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Kembalian;
    private javax.swing.JButton backButton;
    private javax.swing.JButton bayarButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField pembayaran;
    private javax.swing.JTextField uangBayar;
    // End of variables declaration//GEN-END:variables
}
