/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kasir;

import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author HamFin18
 */
public class BeliBarang extends javax.swing.JFrame {

    /**
     * Creates new form BeliBarang
     */
    public BeliBarang()
    {
        initComponents();
    }
    public BeliBarang(String user) {
        initComponents();
       this.user = user;
       modelPembelian = new DefaultTableModel();
       pembelian.setModel(modelPembelian);  
       modelPembelian.addColumn("ID");
       modelPembelian.addColumn("Nama barang");
       modelPembelian.addColumn("Harga");
       modelPembelian.addColumn("Stok");
       modelPembelian.addColumn("Kategori");
       
       modelKeranjang = new DefaultTableModel();
       keranjang.setModel(modelKeranjang);  
       modelKeranjang.addColumn("ID");
       modelKeranjang.addColumn("Nama barang");
       modelKeranjang.addColumn("Harga");
       modelKeranjang.addColumn("Jumlah");
       modelKeranjang.addColumn("Total per item");
       
       awalan();
       }
    DefaultTableModel modelPembelian, modelKeranjang;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textCari = new javax.swing.JTextField();
        hapus = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        keranjang = new javax.swing.JTable();
        cari = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        pembelian = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        tambah = new javax.swing.JButton();
        bayar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Kasir IndoMabar");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        textCari.setText("Cari Barang");
        textCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textCariActionPerformed(evt);
            }
        });

        hapus.setText("Hapus");
        hapus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hapusMouseClicked(evt);
            }
        });
        hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusActionPerformed(evt);
            }
        });

        keranjang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        keranjang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                keranjangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(keranjang);

        cari.setText("Cari");
        cari.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cariMouseClicked(evt);
            }
        });

        pembelian.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        pembelian.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(pembelian);

        jLabel1.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 24)); // NOI18N
        jLabel1.setText("Keranjang Belanja");

        tambah.setText("Tambah ke Keranjang");
        tambah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tambahMouseClicked(evt);
            }
        });
        tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahActionPerformed(evt);
            }
        });

        bayar.setText("Bayar");
        bayar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bayarMouseClicked(evt);
            }
        });
        bayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bayarActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 24)); // NOI18N
        jLabel2.setText("Pembelian");

        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 476, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(textCari, javax.swing.GroupLayout.PREFERRED_SIZE, 476, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bayar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cari, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(hapus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tambah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(backButton))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2))
                    .addComponent(backButton))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textCari, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cari, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tambah, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(bayar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void textCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textCariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textCariActionPerformed

    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hapusActionPerformed

    private void tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahActionPerformed
        // TODO add your handling code here:
        DefaultTableModel zz = (DefaultTableModel)pembelian.getModel();
        int baris = pembelian.getSelectedRow();
        
        String cek = JOptionPane.showInputDialog("Masukkan jumlah barang");
        String stok = (String)zz.getValueAt(baris, 3);
        int j  = Integer.parseInt(stok);
        
        if(j <= Integer.valueOf(cek))
        {
            JOptionPane.showMessageDialog(this, "Stok tidak mencukupi atau habis!");
        }
        else
        {
            String[] x = new String[5]; 
            for (int i=0; i<3; i++)
            {
                x[i] = zz.getValueAt(baris, i).toString();
            }
            x[3] = cek;
            x[4] = String.valueOf(Double.valueOf(x[3]) * Double.valueOf(x[2]));
            modelKeranjang.addRow(x);
        }
        
    }//GEN-LAST:event_tambahActionPerformed

    private void bayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bayarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bayarActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        //dispose();
        
        Tabel.login_pegawai x = new Tabel.login_pegawai();
        Kontrol.kontrol_login_pegawai y = new Kontrol.kontrol_login_pegawai();
        
        try
        {
            String query = "select * from login_pegawai where username = '"+user+"'";
            rs = y.execQuery(query);
            rs.first();
            
            if(rs.getString("kategori").equals("admin"))
            {
                MenuAdmin b=new MenuAdmin(user);
                b.setVisible(true);
            }
            else
            {
                Menu b = new Menu(user);
                b.setVisible(true);
            }
            setVisible(false);
        }
        catch(SQLException ex)
        {
            System.out.println("Error : "+ex);
        }
        
    }//GEN-LAST:event_backButtonActionPerformed

    private void bayarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bayarMouseClicked
        // TODO add your handling code here:
        int jumlah = keranjang.getRowCount();
        
        DefaultTableModel getBarang = (DefaultTableModel)keranjang.getModel();
        
        String[][] x = new String[jumlah][5];
        for (int i=0; i<jumlah; i++)
        {
            for(int j=0; j<5; j++)
            {
                x[i][j]= String.valueOf(getBarang.getValueAt(i, j));
            }
            
        }
        Bayar b=new Bayar(jumlah,x,user);
        b.setVisible(true);
    }//GEN-LAST:event_bayarMouseClicked
Kontrol.kontrol_barang barang;
ResultSet rs;
    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        
    }//GEN-LAST:event_formWindowActivated

 private void awalan()
 {
     String query = "select * from barang";
        
        barang = new Kontrol.kontrol_barang();
        
        try
        {
            //modelPembelian.getDataVector().removeAllElements();
            rs = barang.execQuery(query);
      
            while(rs.next())
            {
                Object[] x = new Object[5];
                x[0] = rs.getString("id");
                x[1] = rs.getString("nama");
                x[2] = rs.getString("harga_jual");
                x[3] = rs.getString("stok");
                x[4] = rs.getString("kategori");
                modelPembelian.addRow(x);
            }
        }
        catch(SQLException e)
        {
            JOptionPane.showMessageDialog(null, "Barang gagal ditampilkan error : "+e);
        }
 }
 private String user;
    
    private void cariMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cariMouseClicked
        String a = textCari.getText();
        String query = "select * from barang where id like '%"+a+"%' or nama like '%"+a+"%' or harga_jual like '"+a+"' or kategori like '%"+a+"%'";
        
        barang = new Kontrol.kontrol_barang();
        
        try
        {
           modelPembelian.getDataVector().removeAllElements();
           rs = barang.execQuery(query);
            
            while(rs.next())
            {
                Object[] x = new Object[5];
                x[0] = rs.getString("id");
                x[1] = rs.getString("nama");
                x[2] = rs.getString("harga_jual");
                x[3] = rs.getString("stok");
                x[4] = rs.getString("kategori");
                modelPembelian.addRow(x);
            }
            rs.close();
        }
        catch(SQLException e)
        {
            JOptionPane.showMessageDialog(null, "Barang gagal ditampilkan error : "+e);
        }
    }//GEN-LAST:event_cariMouseClicked

    private void tambahMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tambahMouseClicked

    }//GEN-LAST:event_tambahMouseClicked

    private void keranjangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_keranjangMouseClicked
        
    }//GEN-LAST:event_keranjangMouseClicked

    private void hapusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hapusMouseClicked
       
       int select = keranjang.getSelectedRow();
       
       if (select==-1)
       {
           int row = keranjang.getRowCount();
           
           for (int i = 0; i<row; i++)
           {
               modelKeranjang.removeRow(0);
           } 
       }
       else
       {
           modelKeranjang.removeRow(select);
       }
    }//GEN-LAST:event_hapusMouseClicked

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BeliBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BeliBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BeliBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BeliBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BeliBarang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JButton bayar;
    private javax.swing.JButton cari;
    private javax.swing.JButton hapus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable keranjang;
    private javax.swing.JTable pembelian;
    private javax.swing.JButton tambah;
    private javax.swing.JTextField textCari;
    // End of variables declaration//GEN-END:variables
}
