/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kasir;

import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author HamFin18
 */
public class ListPegawai extends javax.swing.JFrame {

    /**
     * Creates new form ListAdmin
     */
    public ListPegawai() {
        initComponents();
    }
    
    public ListPegawai(String admin)
    {
        initComponents();
        this.admin = admin;
        
        listPegawai = new DefaultTableModel();
        tabelPegawai.setModel(listPegawai);
        listPegawai.addColumn("ID");
        listPegawai.addColumn("Nama");
        listPegawai.addColumn("gender");
        listPegawai.addColumn("alamat");
        listPegawai.addColumn("email");
        listPegawai.addColumn("No HP");
        
        panggil();
    }
    
    private void panggil()
    {
        listPegawai.getDataVector().removeAllElements();
        pegawai = new Kontrol.kontrol_pegawai();
        String query = "select * from pegawai";
        try
        {
            ResultSet rs = pegawai.execQuery(query);
            
            while(rs.next())
            {
                Object[] x = new Object[6];
                
                x[0] = rs.getString("id");
                x[1] = rs.getString("nama");
                x[2] = rs.getString("gender");
                x[3] = rs.getString("alamat");
                x[4] = rs.getString("email");
                x[5] = rs.getString("no_hp");
                listPegawai.addRow(x);
            }
        }
        catch(SQLException ex)
        {
            System.out.println("Isi tabel gagal dipanggil, error : "+ex);
        }
    }
    Kontrol.kontrol_pegawai pegawai;
    DefaultTableModel listPegawai;
    private String admin;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        back = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelPegawai = new javax.swing.JTable();
        hapus = new javax.swing.JButton();
        update = new javax.swing.JButton();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Kasir IndoMabar");

        jLabel1.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 24)); // NOI18N
        jLabel1.setText("List Admin");

        back.setText("Back");
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
        });
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        tabelPegawai.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabelPegawai);

        hapus.setText("Hapus");
        hapus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hapusMouseClicked(evt);
            }
        });

        update.setText("Update");
        update.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updateMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 552, Short.MAX_VALUE)
                .addComponent(back))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(update, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {hapus, update});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel1))
                    .addComponent(back))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(update)))
                .addGap(0, 60, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {hapus, update});

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_backActionPerformed

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked
        // TODO add your handling code here:
        //dispose();
        OpsiAdmin b=new OpsiAdmin(admin);
        b.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_backMouseClicked

    private void hapusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hapusMouseClicked
        // TODO add your handling code here:
        int row = tabelPegawai.getSelectedRow();
        
        Runnable r = () -> {
            String html = "<html><body width='150'>"
                +"<p>meskipun akan ada pesan data telah terhapus"
                + " Isi tabel tidak akan terhapus"
                + "jika akun dari pegawai belum dihapus</p><br>"
                +"<br><br><p>pastikan akun telah terhapus terlebih dahulu</p>";
            // change to alter the width 
            int w = 150;

            JOptionPane.showMessageDialog(null, String.format(html, w, w));
        };
        SwingUtilities.invokeLater(r);
        int confirm = JOptionPane.showConfirmDialog(null, "Kamu yakin menghapus "+String.valueOf(tabelPegawai.getValueAt(row, 0))+"? ", "WARNING", JOptionPane.YES_NO_OPTION);
        
        if (confirm == JOptionPane.YES_OPTION)
        {     
            Tabel.pegawai x = new Tabel.pegawai();
            
            x.set_id_pegawai(String.valueOf(tabelPegawai.getValueAt(row, 0)));
            pegawai.delete_pegawai(x);
            JOptionPane.showMessageDialog(this, "data telah terhapus!");
        }
    }//GEN-LAST:event_hapusMouseClicked

    private void updateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateMouseClicked
        // TODO add your handling code here:
        int row = tabelPegawai.getSelectedRow();
        int confirm = JOptionPane.showConfirmDialog(null, "Kamu yakin mengubah "+String.valueOf(tabelPegawai.getValueAt(row, 0))+"? ", "WARNING", JOptionPane.YES_NO_OPTION);
        
        if (confirm == JOptionPane.YES_OPTION)
        {     
            Tabel.pegawai x = new Tabel.pegawai();
            x.set_id_pegawai(String.valueOf(tabelPegawai.getValueAt(row, 0)));
            x.set_nama_pegawai(String.valueOf(tabelPegawai.getValueAt(row, 1)));
            x.set_gender_pegawai(String.valueOf(tabelPegawai.getValueAt(row, 2)));
            x.set_alamat_pegawai(String.valueOf(tabelPegawai.getValueAt(row, 3)));
            x.set_email_pegawai(String.valueOf(tabelPegawai.getValueAt(row, 4)));
            x.set_no_hp_pegawai(String.valueOf(tabelPegawai.getValueAt(row, 5)));
            pegawai.update_pegawai(x);
            JOptionPane.showMessageDialog(this, "data telah terupdate");
            panggil();
        }
    }//GEN-LAST:event_updateMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListPegawai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListPegawai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListPegawai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListPegawai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListPegawai().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JButton hapus;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelPegawai;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
